language: java
jdk: openjdk8
script:
- "./mvnw clean install -B -DskipTests"
deploy:
  provider: heroku
  api_key:
    secure: SB8rk54X1Om9Lbw/1NK5sphWShNksiB+DoodZ1DXAb7pPM9N680qsf2ISj6zsRN99yIlZ/e35tFUS7RhPbqBiRU4EnOMycpAPdk/DIrfaKVHBvRSRbXPTwHwLs/s1pawX+TMK65f89Qx6+KX3qBk4rBZcJRv5ZHhjxmyiTbEKwlTAq1d4hgYRUsibfhpTSWXV5GclIOztw/3sjiGS7PXIKyux6UBFxSJ2z1EvIgfE03pa2KVIHJYf55ojrWgvX6fqMDY3jTV+3OM4AkoujQH5YTLNF3hda5RrVC30akOCl9/OiWZVdMpd+K5CNbrsEgWO0v5/B7PE6NGlfgfQR0qRRL9916lwBdPP7csCeKJIcTNMw1y2JYmeFAIRwfpZbET8jlZ+u/GELgtTbU9FZaKFW7HnuG5wBHWDbRTIy6kGQuBzqZtDineu9F6UG1YDKxKUB2+iF8a/5CvyQ11LEfrrRyznxR6FWv2BtwgguF96UXRAOHz9SU2mXyN9DRfJvOmIBcOTWTPe7eBmhNQgM52ZCPFntiKkE7aAvTZfVZHmgtQ7oGs7mNQstF/kEXK3wsOU9MDsdighga0cN6DzrcWCR09/Z0tvolkHormeO1kiPA/e6+WLbg2jG3leSNi9S6cV9ig5/lDYfH19Lhacy4K0OFCXVfAAzp7XYy0Wr2NpYI=
  app: spring-demo-ci
