language: java
jdk: openjdk8
script:
- "./mvnw clean install -B -DskipTests"
deploy:
  provider: heroku
  api_key:
    secure: O+ifbnRAcLB8zOZ3mbg+D18h1ONnYlHto3d2H4crWK+BvNDUMh0E2jSSOA3Vn6TudL7KKp58hyxQ8pJIZ8G5N1xJTBIlUGCOnteGgplv/sw7o0erkc4I21JeRItCRSJudNISeD5Mv1WtDWR6K/4Zpn9hvUugwGs9EaAvM3/fEuhScC/VG/6XUwxLEiQivKts2DJ3wv6FkJPBQOr8R7SHEqumeJY8PhiRJEPeVFCIXOltmLPjOeU0QFdtSPiu7I4h4ZeEhybwx5mo19bzoHodMlLS7ymzfS2fVIziBM3DxkL7Xifbc0GZgJrLu5D3JhVVa4pNbtv20G/FpnEK+n6h/IoCDF2oqnqvPx+3SbXuasA6QDSUmnn3l+2MjGCyNo7IOn4YKOx1bmtM6f5YzggPTHLVbwUbXr+1TfJJolkfhJKHItrpxI6WwGAz3OAYFPoYsTcwn4Gxu8BTHykFsGnRyo1jyyC3Y+4JN2VBiwLVJUtzio6uGNCE9eG4FtVHVmUv0PbFQ5dSwPF9X+LGowW+KFX0fHFLHab7i3qOQ9hYuL2kLwxcfH42SqouAlY76XFEshMYZHnkxQzJrM0fQSdWCX48T+b3MLSGSh2OMd3d3uTMSkY84euDoiG/vxXR2hZtt48KGb31JDZCSvzJvFIGNQrBhfZ75NJKPo/1vIPnnyo=
  app: spring-demo-ci
  on:
    repo: EmreErinc/spring-demo
