language: java
jdk: openjdk8
script:
- "./mvnw clean install -B -DskipTests"
deploy:
  provider: heroku
  api_key:
    secure: s3BF8zcVuweyovH/QCPc5OaZ66CJEwBUE2h+a2kyxkMORmtiLaQyVEwmHQhdYy8oImJxBGV08fnD97Nbl4dfd0vjAbBxU/KsVxVyg9t120kgTr1b7wWfVdBfWDLNy7uebi9mvIMCPo+zibuJInlCRQVMueHz12wqcZ11/JTVea2yTDMRTJ5UkD0uMWdolbweQKWo+6ZV4RXyBm43+rVFdxzf0K18D9JHkBuJtuYRC52eD6A1W/k0Tw4Li0UIJ9GrqAIxbLMN+IxFPkOVMHJjLMNvxOQPgzX+TrlN6wP/KqoKlrEboVPsa5aMcYJ/TlcZMuPjnt67gzltL369MWBjZyRdss/kDd8uuScNsv9uVbKsjHqbQD0cG65iqCweQ9vzOE3CFlVd0q9Q0gYsD5e59Tnv/Z3x+zlIc+wTtm0r7ZfBXM4IIA2Boss79XRg5rQDkxWKNAI/FlCZlygghFtCtmPwCSDzm3FaT1BzkNFmVNUJkYtdhb5chqtATXSmJEN+ge3Bm29A7VOarUS7RtK/9WmTii5cDHKXvHJbIHo+sqcnEEKkCC5/TopIsJzKTlWV9Gq8MqczMDEkSGWO5PgDOm3eFketj0EkEUJ6bo6GJ4lMHv+LvENiAavpbPC+I6QXVYUcf3Hy3XMNP15G8bFNIie4LwCX1OMXb+SXszV4PwQ=
  app: spring-demo-ci
